const teams = [
  { name: 'América mg', img: 'america_mg' },
  { name: 'América rn', img: 'america_rn' },
  { name: 'Atlético go', img: 'atletico_go' },
  { name: 'Atlético mg', img: 'atletico_mg' },
  { name: 'Atlético pr', img: 'atletico_pr' },
  { name: 'Avaí', img: 'avai' },
  { name: 'Bahia', img: 'bahia' },
  { name: 'Barueri', img: 'barueri' },
  { name: 'Botafogo', img: 'botafogo' },
  { name: 'Brasiliense', img: 'brasiliense' },
  { name: 'Ceará', img: 'ceara' },
  { name: 'Chapecoense', img: 'chapecoense' },
  { name: 'Corinthians', img: 'corinthians' },
  { name: 'Coritiba', img: 'coritiba' },
  { name: 'Criciúma', img: 'criciuma' },
  { name: 'Cruzeiro', img: 'cruzeiro' },
  { name: 'Figueirense', img: 'figueirense' },
  { name: 'Flamengo', img: 'flamengo' },
  { name: 'Fluminense', img: 'fluminense' },
  { name: 'Fortaleza', img: 'fortaleza' },
  { name: 'Goiás', img: 'goias' },
  { name: 'Grêmio prudente', img: 'gremio_prudente' },
  { name: 'Grêmio', img: 'gremio' },
  { name: 'Guarani', img: 'guarani' },
  { name: 'Internacional', img: 'internacional' },
  { name: 'Ipatinga', img: 'ipatinga' },
  { name: 'Joinvile', img: 'joinvile' },
  { name: 'Juventude', img: 'juventude' },
  { name: 'Náutico', img: 'nautico' },
  { name: 'Palmeiras', img: 'palmeiras' },
  { name: 'Paraná', img: 'parana' },
  { name: 'Paysandu', img: 'paysandu' },
  { name: 'Ponte preta', img: 'ponte_preta' },
  { name: 'Portuguesa', img: 'portuguesa' },
  { name: 'Santa cruz', img: 'santa_cruz' },
  { name: 'Santo andré', img: 'santo_andre' },
  { name: 'Santos', img: 'santos' },
  { name: 'São caetano', img: 'sao_caetano' },
  { name: 'São paulo', img: 'sao_paulo' },
  { name: 'Sport', img: 'sport' },
  { name: 'Vasco', img: 'vasco' },
  { name: 'Vitória', img: 'vitoria' },
];

export default teams;
